apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hecate-daemon
  namespace: hecate
  labels:
    app.kubernetes.io/name: hecate-daemon
    app.kubernetes.io/part-of: hecate-system
spec:
  selector:
    matchLabels:
      app: hecate-daemon
  template:
    metadata:
      labels:
        app: hecate-daemon
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      volumes:
        - name: socket-dir
          hostPath:
            path: /run/hecate
            type: DirectoryOrCreate
        - name: data-dir
          hostPath:
            path: /var/lib/hecate
            type: DirectoryOrCreate

      containers:
        - name: daemon
          image: ghcr.io/hecate-social/hecate-daemon:main
          imagePullPolicy: Always

          # Load config from ConfigMaps and secrets
          envFrom:
            - configMapRef:
                name: hecate-config
            - configMapRef:
                name: hecate-hardware
                optional: true  # Applied by install script, node-specific
            - secretRef:
                name: hecate-api-keys
                optional: true  # Contains commercial LLM API keys

          # Pod-specific env vars
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          # Ports omitted - daemon binds to host network directly
          # - 4433: mesh (QUIC/UDP)
          # - 9443: QUIC listener
          # TCP API removed for security - Unix socket only

          volumeMounts:
            - name: socket-dir
              mountPath: /run/hecate
            - name: data-dir
              mountPath: /var/lib/hecate

          # Health checks via socket file presence
          # Socket only appears when daemon is ready and serving
          livenessProbe:
            exec:
              command:
                - test
                - -S
                - /run/hecate/daemon.sock
            initialDelaySeconds: 10
            periodSeconds: 30

          readinessProbe:
            exec:
              command:
                - test
                - -S
                - /run/hecate/daemon.sock
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
